name: abdulrauf-portfolio
region: fra
static_sites:
  - name: portfolio
    github:
      repo: qrauf/AbdulRaufQureshi
      branch: main
      deploy_on_push: true
    source_dir: /
    index_document: index.html
    error_document: index.html
